### ISSUE TITLE
Setting currency in sats for a TPos leads to issues creating items in a TPos instance

### ISSUE THREAD

**Issue by CabtonWithaK** [lnbits/tpos#104]
AS IS:
a TPOS item is correctly added when currency is set to 'USD'. 
a TPOS item is however not added when the currency is set to 'sats'

TO BE: 
Items can be added when currency is set to 'sats' for a TPOS instance.

ELABORATE:

I noticed this issue on LNBits SaaS 0.12.12, when I changed the currency of my TPos to "sats" suddenly all my TPOS items disappeared.
Also when I created a new TPOS I noticed items can not be added when currency is set to sats.

find screenshot attached for error that I found in my debug console

![TPOS_sats](https://github.com/user-attachments/assets/6d5ad02b-dc2a-4245-9146-6a8e6dc3a99c)

**Comment by talvasconcelos** [comment]
I'm on it... investigating

**Comment by talvasconcelos** [comment]
Fixed in 0.7.2
