### ISSUE TITLE
TPOS EUR to sat conversion issues

### ISSUE THREAD

**Issue by CabtonWithaK** [lnbits/tpos#106]
Often the conversion of eur to sat does not seem to work properly on TPos (see image attached).
The amount in euro is not converted to the correct amount of sats.
This is a concern because the amount in euro's is correct on the POS device, however the wrong amount in sats is eventually charged

After some page refresh attempts, sometimes the conversion is successful. I assume this has to do with a correct handling of API call to the endpoint _xx-lnbits.com/tpos/api/v1/rate/EUR_  which is often delayed.

Observed on LNBits v. 0.12.12 (current SaaS version), in Chrome (Windows and Android)

![lnbits_TPOS_issue_rate_sats_EUR](https://github.com/user-attachments/assets/0d74db11-ba2a-4d27-b4f0-24bd25151222)

**Comment by talvasconcelos** [comment]
Fixed in 0.7.2
