### ISSUE TITLE
When TPOS currency is set to "sats" the total invoice amount is incorrect

### ISSUE THREAD

**Issue by CabtonWithaK** [lnbits/tpos#107]
When the TPOS currency is set to sats, it seems all amounts >10 get a an additional decimal when invoiced. The added decimal is added after the first decimal

See prt screen attached

10 sats becomes 100 sats (_lnbits_TPOS_issue_sats_10x_a.png_)
50 sats becomes 500 sats (_lnbits_TPOS_issue_sats_10x_b.png_)
12 sats becomes 1**0**2 sats (!?) (_lnbits_TPOS_issue_sats_10x_c.png_)
8 sats remains 8 sats (expected and correct behaviour) (_lnbits_TPOS_issue_sats_10x_d.png_)
34 sats becomes 304 sats (!?) (_lnbits_TPOS_issue_sats_10x_d.png_)

![lnbits_TPOS_issue_sats_10x_d](https://github.com/user-attachments/assets/894c53e3-ac24-4d71-b59e-a2c4c11f1c99)
![lnbits_TPOS_issue_sats_10x_c](https://github.com/user-attachments/assets/45886f58-3560-4bea-8e9a-9a3474e4dd21)
![lnbits_TPOS_issue_sats_10x_b](https://github.com/user-attachments/assets/363dcc11-0d4a-44ba-8905-de00b3cbe297)
![lnbits_TPOS_issue_sats_10x_a](https://github.com/user-attachments/assets/52eb8ee0-9347-42c3-867e-e0018c39af9c)
![lnbits_TPOS_issue_sats_10x_e](https://github.com/user-attachments/assets/f1ec0f86-ed03-4f34-8473-4bfde5bb7b0d)

**Comment by talvasconcelos** [comment]
Fixed in 0.7.2
