### ISSUE TITLE
[Improvement] Reduce click/tap after successful payment

### ISSUE THREAD

**Issue by CabtonWithaK** [lnbits/tpos#111]
**AS IS**
When you Open TPOS > Add items > Shopping Cart > press "Pay" and the invoice is paid > a Screen with a green checkmark is displayed. 
When the checkmark is clicked, you arrive on a screen with amount, "pay" (disabled button), "clear cart" (nonfunctional button)

To go back you need to swipe this screen away

![checkmark](https://github.com/user-attachments/assets/09aa02f3-72c1-4965-87c1-fb20c0178929)

![slide_manual](https://github.com/user-attachments/assets/fd5b5c4a-44a3-4153-91d8-38b02abce44c)

**TO BE**:
When successfully paid and clicked on the checkmark, the screen with amount (0 sats), "pay" (disabled button), "clear cart" (nonfunctional button) should automatically disapear (or slide out)

**Comment by talvasconcelos** [comment]
Fixed for V1 ( #109 )
