### ISSUE TITLE
[Feature Request] onchain capabilties 

### ISSUE THREAD

**Issue by BoyvdR** [lnbits/tpos#25]
I would love to have the option to generate a onchain addresses to receive onchain payments with the tpos extention. 

I know I could use another extension for this specific usecase but it would be nice to have it within the same extension when you want to receive a payment.

**Comment by prusnak** [comment]
I think that on-chain does not belong to TPOS. Amounts paid to merchants at POS are small and you do not want to do that with on-chain.

**Comment by dadofsambonzuki** [comment]
Perhaps a Liquid integration?

**Comment by talvasconcelos** [comment]
@dni :eyes:

**Comment by motorina0** [comment]
> I think that on-chain does not belong to TPOS. Amounts paid to merchants at POS are small and you do not want to do that with on-chain.

I agree
