### ISSUE TITLE
Tips are crediting & debiting at the same time.

### ISSUE THREAD

**Issue by dadofsambonzuki** [lnbits/tpos#3]
Each time a tip is received there is a credit *and* debit entry. The net balance increase from the tip is zero.

<img width="651" alt="Screenshot 2023-03-31 at 15 49 25" src="https://user-images.githubusercontent.com/87125117/229154145-a162fee2-98d6-4e7b-af8d-ab6e88af3472.png">

TPOS version `0.4.0`.

**Comment by dadofsambonzuki** [comment]
I updated the extension to `0.4.1` and now it's double happening!

<img width="651" alt="Screenshot 2023-03-31 at 16 07 24" src="https://user-images.githubusercontent.com/87125117/229158595-e5660e3b-9756-49ad-858c-c844e38fe0fe.png">

I restarted the server and we're now back to single debit/credit txs as per the OP.

@dni - smells similar to the bug you squished in `splits`.

**Comment by talvasconcelos** [comment]
Just tested latest TPOS release and can't reproduce your issue.

**Comment by dni** [comment]
@dadofsambonzuki if you are absolutlty right https://github.com/lnbits/tpos/blob/main/__init__.py

it does not deinitialize at runtime, i gonna fix this tomorrow.

until that restarting your lnbits will fix it!

**Comment by dadofsambonzuki** [comment]
Nice!

When does it reoccur after a restart?

**Comment by dni** [comment]
if you update or reinstall that extension

**Comment by talvasconcelos** [comment]
Closed by #5
