### ISSUE TITLE
LNBits 0.11.2 + TPoS v0.5.1 - Price items can be paid only for only integer type of price

### ISSUE THREAD

**Issue by Perlover** [lnbits/tpos#47]
Hello,

LNBits 0.11.2 + TPoS v0.5.1 - Price items can be paid only for only integer type of price
For example I can add item with price 2.3 but when I go to checkout to cart payment - I see yellow warning at bottom of page that price is not integer type. If I add to cart only integer price items - I can pay

**Comment by talvasconcelos** [comment]
javascript floating point precision BS!!
