### ISSUE TITLE
LNBits 0.11.2 + TPoS v0.5.1 - Deletion of TPoS items - 401 error

### ISSUE THREAD

**Issue by Perlover** [lnbits/tpos#48]
Hello,

LNBits 0.11.2 + TPoS v0.5.1

I created three items in TPoS and when I try to delete some item (I try the 3rd item) - I see 401 error at bottom of page and an item is not deleted.

**Comment by prusnak** [comment]
Fixed in https://github.com/lnbits/tpos/pull/40 

Will be released in TPOS 0.5.2
