### ISSUE TITLE
LNBits 0.11.2 + TPoS v0.5.1 - tips are not separated from the payment and are not sent to a separate wallet if specified in the terminal settings

### ISSUE THREAD

**Issue by Perlover** [lnbits/tpos#51]
Hello,

tips are not separated from the payment and are not sent to a separate wallet if specified in the terminal settings.

I just created a terminal, specified a separate wallet for payment, another for tips, specified tips and paid 10% tip. As a result, one payment was made and the entire amount went to the main wallet. Tips should go separately to the wallet that was specified when creating the terminal.

**Comment by prusnak** [comment]
If confirmed, this sounds like a regression.

**Comment by talvasconcelos** [comment]
Can't reproduce the error:

![tpos](https://i.imgur.com/MMWOAnV.png)

Payment goes in the TPoS wallet, and then it send the tip to the tip wallet! Maybe it's an issue with listeners, if it doesn't "catch" the payment, it doesn't process the tip. A restart fixes it!

**Comment by talvasconcelos** [comment]
Clean TpoS with and without tips!

![tpos](https://i.imgur.com/rMqDKn8.png)

The behaviour of the tips, if i recall and i could be wrong, always worked like that!
