### ISSUE TITLE
TPoS return 1 sat invoice when fiat rate is not fetchable

### ISSUE THREAD

**Issue by DoktorShift** [lnbits/tpos#52]
### Issue:
I am hosting a LnBits Server for small merchants and projects. Today i had a internet collaps for a few seconds. Exactly during this period a client used the TPoS and want to generate a invoice for 30,50€. The logs show me that the rate could not be fetched.

_Logs out of LNBits:_

```
Dez 06 18:50:38 lndbusiness poetry[36414]: 2023-12-06 18:50:38.26 | WARNING | Failed to fetch Bitcoin price for EUR from Binance:
Dez 06 18:50:38 lndbusiness poetry[36414]: 2023-12-06 18:50:38.27 | WARNING | Failed to fetch Bitcoin price for EUR from Blockchain:
Dez 06 18:50:38 lndbusiness poetry[36414]: 2023-12-06 18:50:38.28 | WARNING | Failed to fetch Bitcoin price for EUR from Exir:
Dez 06 18:50:38 lndbusiness poetry[36414]: 2023-12-06 18:50:38.28 | WARNING | Failed to fetch Bitcoin price for EUR from Bitfinex:
Dez 06 18:50:38 lndbusiness poetry[36414]: 2023-12-06 18:50:38.29 | WARNING | Failed to fetch Bitcoin price for EUR from Bitstamp:
Dez 06 18:50:38 lndbusiness poetry[36414]: 2023-12-06 18:50:38.30 | WARNING | Failed to fetch Bitcoin price for EUR from Coinbase:
Dez 06 18:50:38 lndbusiness poetry[36414]: 2023-12-06 18:50:38.30 | WARNING | Failed to fetch Bitcoin price for EUR from CoinMate:
Dez 06 18:50:38 lndbusiness poetry[36414]: 2023-12-06 18:50:38.32 | WARNING | Failed to fetch Bitcoin price for EUR from Kraken:
```

The TPoS returned payable invoice over 1 sat.

_Screen out of thunderhub:_

![Screen TH](https://github.com/lnbits/tpos/assets/106493492/30981f23-6197-48fe-9f2b-199560887329)

The second try, after both, client and customer noticed something went wrong, worked as it should.

### Software:
LNBits 0.11.2
TPoS 0.5.1

**Comment by talvasconcelos** [comment]
That must be some screwed up edge case! I can't reproduce it. Even when i set the exchange rate to `null` it doesn't let me enter a value. 

Can you share the payment extra, by clicking the payment green arrow

![extra](https://i.imgur.com/T3xzeMb.png)

**Comment by DoktorShift** [comment]
Sure.

![payment extra](https://github.com/lnbits/tpos/assets/106493492/f74db0f3-16c0-43d9-b588-fb258f80b053)

**Comment by talvasconcelos** [comment]
The amount was 0!!
