### ISSUE TITLE
Wallet Balance in ATM Mode

### ISSUE THREAD

**Issue by santyr** [lnbits/tpos#54]
It would be useful to have the wallet balance available in ATM mode so one could see how many sats he has available to sell.  This way the seller could avoid errors due to trying to sell more than he has.

**Comment by talvasconcelos** [comment]
TPoS doesn't have wallet access! It's tricky to pull the balance from the wallet, and may pose some privacy issues. 

@arcbtc ?

**Comment by prusnak** [comment]
I don't think we want this. If you want to check the wallet balance, you can do it in the main LNbits view.
