### ISSUE TITLE
max amount to be sold daily and withdraw PIN - are essential values

### ISSUE THREAD

**Issue by tlindi** [lnbits/tpos#74]
`"max amount to be sold daily"`
is marked as mandatory, but if it not filled one gets error
![image](https://github.com/lnbits/tpos/assets/7249767/531483dc-8b3a-49e4-8507-2553768366ed)

**Comment by tlindi** [comment]
Same seems to be the case with withdraw PIN - it is needed to be filled, even it is disabled.

**Comment by talvasconcelos** [comment]
Fixed by #68 ?

**Comment by tlindi** [comment]
> Fixed by #68 ?

no. Originally marking value to mandatory was part of 68 . But was separated to make PR more simple.
