### ISSUE TITLE
Add items to a shopping cart or basket

### ISSUE THREAD

**Issue by Satoshi-Samourai** [lnbits/tpos#8]
It would be nice to have the possibility to create items with a dedicated price to them and combine them into a shop. At checkout the merchant just adds the purchased items into a cart and creates an invoice.

Breez Wallet's PoS is a great example for these options. You can even add custom icons to each item.
(see added screen shot).

This feature could add great value to the adoption of LNBits TPoS.

Thanks for considering.

![Screenshot_20230609-134225_Breez](https://github.com/lnbits/tpos/assets/130285815/cf5c8650-344b-4502-870e-479b94a4da4d)

**Comment by talvasconcelos** [comment]
This may be out of the scope of the extension! it's a cool idea, but maybe there are better suited extensions, or combinations, that could give that capability. Take a look at the Invoice extension lnbits/invoices#

**Comment by arbadacarbaYK** [comment]
> This may be out of the scope of the extension! it's a cool idea, but maybe there are better suited extensions, or combinations, that could give that capability. Take a look at the [Invoices extension](https://github.com/lnbits/invoices).

Being able to add LNURLp´s in the tpos would be a nice thing tbh. 
Especially since the tpos doesnt allow for calculation the sum first and most people buy more than one thing in a cafe.. As a waiter you need to calculate that in your head for a table you have served which is not very common.. This could make it easier for the staff.

![Group 58](https://github.com/lnbits/tpos/assets/63317640/8eeae62e-115e-4af5-ac61-9349f11a52b3)

**Comment by talvasconcelos** [comment]
> > This may be out of the scope of the extension! it's a cool idea, but maybe there are better suited extensions, or combinations, that could give that capability. Take a look at the [Invoices extension](https://github.com/lnbits/invoices).
> 
> Being able to add LNURLp´s in the tpos would be a nice thing tbh. Especially since the tpos doesnt allow for calculation the sum first and most people buy more than one thing in a cafe.. As a waiter you need to calculate that in your head for a table you have served which is not very common.. This could make it easier for the staff.
> 
> ![Group 58](https://user-images.githubusercontent.com/63317640/270111619-8eeae62e-115e-4af5-ac61-9349f11a52b3.png)

Does #30 addresses this feature request?

Basically it adds a (+) button, a merchant can click to keep adding values to the total amount

**Comment by arbadacarbaYK** [comment]
I´d say it helps but its not the same. 

For this request here you do not need to know each price and have access to the most bought things but most of all its much faster to three times press a button than putting in/adding three different values.

Todays fiat terminals allow presaved shortcut-commands to add up products (#1, #12 = 1200 sats) which correlate to the menue #options.
